config/routes.rb
Rails.application.routes.draw do

  resources :users  do
    resources :contacts, only: [:index, :create, :new, :edit, :update]
  end
  resources :contacts, only: [:destroy, :show]

  resources :contact_shares, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ref, polymorphic: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, :name, :user_id, presence: true
  validates :email, uniqueness: { scope: :user_id }

  belongs_to :owner,
  class_name: :User,
  foreign_key: :user_id

  has_many :contact_shares, dependent: :destroy

  has_many :shared_users,
  through: :contact_shares,
  source: :user

  has_many :comments, as: :ref

end

app/models/contact_share.rb
class ContactShare < ActiveRecord::Base

  validates :contact_id, :user_id, presence: true
  validates :user_id, uniqueness: { scope: :contact_id }

  belongs_to :contact
  belongs_to :user

  has_many :comments, as: :ref

end

app/models/group.rb
class Group < ActiveRecord::Base

  belongs_to :user
  has_many :group_contacts
  has_many :contacts, through: :group_contacts

  def add(contact)
    gc = GroupContact.new(group_id: id, contact_id: contact.id)
    gc.save
  end

end

app/models/group_contact.rb
class GroupContact < ActiveRecord::Base

  belongs_to :contact
  belongs_to :group

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true, uniqueness: true

  has_many :contacts, dependent: :destroy
  has_many :contact_shares, dependent: :destroy

  has_many :shared_contacts,
  through: :contact_shares,
  source: :contact

  has_many :comments, as: :ref
  has_many :groups

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/contact_shares_controller.rb
class ContactSharesController < ApplicationController

  def create
    contact_share = ContactShare.new(contact_share_params)
    if contact_share.save
      render json: contact_share
    else
      render json: contact_share.errors.full_messages
    end
  end

  def destroy
    contact_share = ContactShare.find_by(:id, params[:id])
    if contact_share.save
      render json: contact_share
    else
      render json: contact_share.errors.full_messages
    end
  end

  private
  def contact_share_params
    params.require(:contact_share).permit(:user_id, :contact_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :get_user, only: [:index, :create, :new, :edit, :update]
  before_action :get_contact, only: [:show, :update, :destroy, :edit]

  def index
    all_contacts = @user.contacts + @user.shared_contacts
    render json: all_contacts
  end

  def show
    render json: @contact
  end

  def create
    contact = @user.contacts.new(contact_params)
    if contact.save
      redirect_to @user
    else
      render json: contact.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
  end

  def new
    @contact = Contact.new
  end

  def update
    if @contact.update(contact_params)
      redirect_to @user
    else
      render json: @contact.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    if @contact.destroy
      redirect_to @contact.owner
    else
      render json: @contact.errors.full_messages
    end
  end

  private


  def get_user
    @user = User.find_by(id: params[:user_id])
  end

  def get_contact
    @contact = Contact.find_by(id: params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :update, :destroy, :edit]

  def index
    @users = User.all
  end

  def show
  end

  def create
    user = User.new(user_params)
    if user.save
      render json: user
    else
      render json: user.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.destroy
      render json: @user
    else
      render json: @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
  end

  def new
    @user = User.new
  end

  private
  def user_params
    params.require(:user).permit(:username)
  end

  def find_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_shares_helper.rb
module ContactSharesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact, url: user_contacts_url(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>
<%= form_for @contact, url: user_contact_url(@user, @contact) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit %>
<% end %>

app/views/contacts/new.html.erb
<h1>Create Contact</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BabysFirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.submit %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<table>
  <thead>
    <th>Username</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= button_to 'Create User', new_user_url, method: :get %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h3>Contacts</h3>
<table>
  <thead>
    <tr>
      <th>
        name
      </th>
      <th>
        email
      </th>
      <th>
        Action
      </th>
    </tr>
  </thead>
  <tbody>
    <% @user.contacts.each do |contact| %>
      <tr>
        <td>
          <%= contact.name %>
        </td>
        <td>
          <%= contact.email %>
        </td>
        <td>
          <%= button_to 'Delete', contact, method: :delete %>
        </td>
        <td>
          <%= button_to 'Edit', edit_user_contact_url(@user, contact), method: :get %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<h3>Shared Contacts</h3>
<table>
  <thead>
    <tr>
      <th>
        name
      </th>
      <th>
        email
      </th>
    </tr>
  </thead>
  <tbody>
    <% @user.shared_contacts.each do |contact| %>
      <tr>
        <td>
          <%= contact.name %>
        </td>
        <td>
          <%= contact.email %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= button_to 'Create Contact', new_user_contact_url(@user), method: :get %>
<%= button_to 'back', users_url, method: :get %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>